name: Yumgott
description: Restaurant application where users and restaurants can make accounts, so user can shop and restaurant can sell his Food to them.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0

environment:
  sdk: ">=2.17.0 <3.0.5 "

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: ^0.18.0


  ## built_value: ^8.1.4
  built_value: ^8.2.3


  #Compress Video
  video_compress: ^3.1.0

  #keyboard SiZE
  flutter_keyboard_visibility: ^5.4.1
  fluttertoast: ^8.2.2

  #DateTime picker
  flutter_cupertino_datetime_picker: ^3.0.0


  #Reels display in Effective Way
#  vimeo_player_flutter: ^0.0.3+2
#  vimeo_video_player: ^0.0.10

  dio_cookie_manager: ^2.0.0
  cookie_jar: ^3.0.1
  freezed: ^2.0.3+1
  url_launcher: ^6.0.20
  carousel_slider: ^4.1.1
  chewie: ^1.3.4
  dots_indicator: ^2.1.0


  #Google maps
  google_maps_flutter: ^2.2.8

  #Image picker
  image_picker: ^0.8.4+11

  #Voice Messages
  #  voice_message_package: 0.0.74
  syncfusion_flutter_core: ^20.4.53

  #flutter_audio_recorder2: ^0.0.2
  syncfusion_flutter_sliders: ^20.4.53

  #UI
  multiselect: ^0.1.0
  cached_network_image: ^3.0.0


  # for Dependency injection
  get_it: ^7.2.0


  #Logic
  #country_codes: ^2.0.1
  flutter_svg: ^1.0.3
  google_fonts: ^4.0.3





  #Fonts


  #logic
  lat_lng_to_timezone: ^0.2.0
  flutter_fgbg: ^0.2.0


  # The following adds the Cupertino Icons font to your application.



  #social Login
  the_apple_sign_in: ^1.1.1
  google_sign_in: ^5.3.1
  flutter_login_facebook: ^1.6.1
  sign_in_with_apple: ^4.0.0
  flutter_signin_button: ^2.0.0
  flutter_insta: ^1.0.1
  twitter_login: ^4.2.3
  github: ^9.4.0



  #sdks
#  gleap_sdk: ^7.0.13
#

  # StateManagemant Packages
  flutter_bloc: ^7.1.0
  bloc: ^7.2.0
  json_serializable: ^6.1.5


  # http Packages
  dio: ^5.2.0+1

  #Local Database
  shared_preferences: ^2.0.6



  #string_extensions: ^0.6.2
  flutter_spinkit: ^5.0.0




  # UI packages
  animated_snack_bar: ^0.2.2
  dropdown_button2: ^1.9.4
  tapioca: ^1.0.6+1
  camera: ^0.10.3+2
  wechat_assets_picker: ^8.5.0
  internet_connection_checker: ^0.0.1+3
  flutter_staggered_grid_view: ^0.4.0
  like_button: ^2.0.5
  timeago: ^3.3.0
  sliding_up_panel: ^2.0.0+1
  form_field_validator: ^1.1.0
  location: ^4.4.0
  flutter_rating_bar: ^4.0.1


  #Vidoe making and Filtters


  #Video
  video_player: ^2.6.1

  #Status Code manager
  http_status_code: ^0.0.2





  ## notifications:
  flutter_local_notifications: ^9.4.0
  flutter_app_badger: ^1.4.0
  badges: ^2.0.3



  ## awesome_notifications: ^0.6.21


  #Responsive UI
  flutter_screenutil: ^5.5.4

  #firebase
  firebase_messaging: ^14.2.5
  firebase_core: ^2.7.0
  firebase_auth: ^4.2.9
  firebase_dynamic_links: ^5.0.17

  #Sync Contacts
  #contacts_service: ^0.6.3
  #flutter_contacts: ^1.1.4

  share_plus: ^4.0.4
#  sms_autofill: ^2.2.0
#  flutter_email_sender: ^5.1.0



  intl_phone_number_input: ^0.7.1
  fijkplayer: ^0.10.0


  #App Updates
  in_app_update: ^4.0.1


  #Permition handler
  geolocator: ^9.0.1
  geocoding: ^2.0.4
  geocoder2: ^1.4.0
  permission_handler: ^10.0.0
  path_provider: ^2.0.9

  #animation
  lottie: ^1.4.0



  cupertino_icons: ^1.0.2




dev_dependencies:
  analyzer: ^4.1.0
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.1
  build_runner: ^2.2.0
  built_value_generator: ^8.4.1


flutter:
  #  generate : true
  uses-material-design: true

  assets:
    - Assets/images/
    - Assets/videos/
    - Assets/Lottie/
    - lib/core/Language/lang/



#
#  fonts:

#    - family: SF Pro Display
#      fonts:
#        - asset: Assets/Fonts/SFPRODISPLAYBLACKITALIC.OTF
#
#
#    - family: Helvetica
#      fonts:
#        - asset: Assets/Fonts/Helvetica.ttf
#
#    - family: IBM Plex Sans
#      fonts:
#        - asset: Assets/Fonts/IBMPlexSans-Regular.ttf
#
#
#    - family: SF Pro Text
#      fonts:
#        - asset: Assets/Fonts/FontsFree-Net-SFProText-Regular.ttf
#
#    - family: Roboto Medium
#      fonts:
#        - asset: Assets/Fonts/Roboto-Medium.ttf
#
#    - family: Red Hat Text
#      fonts:
#        - asset: Assets/Fonts/RedHatText-Regular.ttf
#
#    - family: Red Hat Display
#      fonts:
#        - asset: Assets/Fonts/RedHatDisplay-Regular.ttf