// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAq71baCwAKFjqaMTL1ZE22milJtldWQpE',
    appId: '1:607731009626:web:31ceb939fed73a7ea2b063',
    messagingSenderId: '607731009626',
    projectId: 'yumgott-ee607',
    authDomain: 'yumgott-ee607.firebaseapp.com',
    storageBucket: 'yumgott-ee607.appspot.com',
    measurementId: 'G-05MKRDMJED',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZVebPBd02whlDy5Il_vS2EaAN480D5zU',
    appId: '1:607731009626:android:dbfbb4d6f1521dc5a2b063',
    messagingSenderId: '607731009626',
    projectId: 'yumgott-ee607',
    storageBucket: 'yumgott-ee607.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHeTwGBCo2e5tCULdRY-v7hE-9ZDQaPcM',
    appId: '1:607731009626:ios:d2f6fcef7a3df713a2b063',
    messagingSenderId: '607731009626',
    projectId: 'yumgott-ee607',
    storageBucket: 'yumgott-ee607.appspot.com',
    iosClientId: '607731009626-ou6641j657si2c0pic3is8586koeso9j.apps.googleusercontent.com',
    iosBundleId: 'com.ActiveHub.logo',
  );
}
